FROM python:3.8.2

RUN mkdir /app
WORKDIR /app

COPY app.py boot.sh wsgi.py user_data.py requirements.txt ./
COPY assets assets

RUN pip install -r requirements.txt
RUN chmod +x boot.sh

EXPOSE 80
ENTRYPOINT ["./boot.sh"]